### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jongeselle**
Just cleaned up some of the language to align with the RFP. There may still need to be edits to the documentation and background sections - I didn't address Nick's comments on PR #3

### CODE REVIEW

**Comment by nfaulknerAK** [comment]
This looks great. I saw one typo, but I can address after Randy reviews and merges.

**Comment by jongeselle** [comment]
I did question whether adding "Eligibility Information System" to the background was the right thing. I was trying to be clear that the multiple solicitations will be in service of this project.

**Comment by nfaulknerAK** [comment]
I think that change is right on. I like keeping the repos and solicitations clean now, so that we are able to scale easier in the future. The comments about the wiki etc we can just address in practice. adding any of that just clutters things up.

**Comment by randyhart** [comment]
looks great.  nice catches.

**Pull request merged**
