### PR TITLE
Update Amendment 2 - Include Additional Prototype Findings

### PR DESCRIPTION
**Pull request by mheadd**
The purpose of this Pull Request is to amend the RFP documents, specifically the prototype findings document, to add additional details and clarify background information.

### CODE REVIEW

**Comment by jongeselle** [comment]
Mark- I think we need to change the title of this PR. Since the changes made in this PR are included in Amendment 2, I don't want folks to be confused that there was a third amendment.

**Comment by jongeselle** [comment]
Maybe it could be Amendment 2 - Prototype Findings

**Comment by randyhart** [comment]
@jongeselle @mheadd how about that as a Title for this PR?

**Comment by jongeselle** [comment]
That works.

**Pull request merged**
