### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by randyhart**
Explains that some of the referenced documentation is intentionally subject to change, even while the RFP is out for bid.

### CODE REVIEW

**Comment by jongeselle** [comment]
I have a couple of minor changes I'd like to make. What's the easiest way to do this? Merge and then edit or is there a way to edit your edits?

**Comment by randyhart** [comment]
There's a way to edit my edits - but I think the easiest way (out of expediency) is just to merge, then edit.

**Comment by jongeselle** [comment]
I'll let Nick weigh in before I merge.

**Comment by nfaulknerAK** [comment]
looks good but I think we should reference the vendor update in the wiki if we intend to keep doing that with this repo. We might be more clear about what we think could actually change, with the RFP and QAP and IT standards remaining unless we find an error which will be handled in an issue? I just want to make sure we are clear about what might realistically change, and the impact it might have.

**Comment by jongeselle** [comment]
I'll go ahead and merge and then we can refine the language.

**Pull request merged**
