### PR TITLE
Add an appendix, including sample API responses

### PR DESCRIPTION
**Pull request by waldoj**
This will demonstrate to bidders what the existing API responses look like, both in the standard Alaska environment and also within our prototype.

This is toward #33.

### CODE REVIEW

**Comment by jongeselle** [comment]
Looks great. This gives me enough to add a note in Amendment 2 to identify the addition of the info.

**Comment by ctro** [comment]
@jongeselle this is ready to go if it looks good to you!

**Comment by jongeselle** [comment]
This looks good to me, but I'd like one of the technical folks to take a peek too.

**Comment by mheadd** [comment]
In the `Components` section, we describe EIS as a "Natural/ADABAS system running on the state mainframe" but in the Appendix we describe EIS as "built atop COBOL and Adabas." Not sure if this level of detail on the system is relevant since vendors will likely only interact with EIS through a service layer but wanted to make sure we were consistent.

**Comment by waldoj** [comment]
I modified that COBOL/Abadas reference to make it consistent.

**Comment by sztaylorakgov** [comment]
Regarding COBOL and Natural, I believe both are true.  Typically, COBOL is used to construct the application user-interface "green screens" and Natural is used to manipulate data.

**Review by sztaylorakgov — APPROVED** [review]
I didn't have time to go through the entire doc, but I did get the COBOL and Natural comment addressed.

**Pull request merged**
